//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestShopService.BookConctractor {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Book", Namespace="http://schemas.datacontract.org/2004/07/Shop.Web.BLL.Data.Models")]
    [System.SerializableAttribute()]
    public partial class Book : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BookType", Namespace="http://schemas.datacontract.org/2004/07/Shop.Web.BLL.Data.Enum")]
    public enum BookType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AudioBooks = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        EBooks = 2,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="BookConctractor.IBookContractor")]
    public interface IBookContractor {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBookContractor/GetAllBooks", ReplyAction="http://tempuri.org/IBookContractor/GetAllBooksResponse")]
        TestShopService.BookConctractor.Book[] GetAllBooks();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBookContractor/GetAllBooks", ReplyAction="http://tempuri.org/IBookContractor/GetAllBooksResponse")]
        System.Threading.Tasks.Task<TestShopService.BookConctractor.Book[]> GetAllBooksAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBookContractor/FindBooks", ReplyAction="http://tempuri.org/IBookContractor/FindBooksResponse")]
        TestShopService.BookConctractor.Book[] FindBooks(TestShopService.BookConctractor.BookType bookType, string title, string publisher);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBookContractor/FindBooks", ReplyAction="http://tempuri.org/IBookContractor/FindBooksResponse")]
        System.Threading.Tasks.Task<TestShopService.BookConctractor.Book[]> FindBooksAsync(TestShopService.BookConctractor.BookType bookType, string title, string publisher);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IBookContractorChannel : TestShopService.BookConctractor.IBookContractor, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BookContractorClient : System.ServiceModel.ClientBase<TestShopService.BookConctractor.IBookContractor>, TestShopService.BookConctractor.IBookContractor {
        
        public BookContractorClient() {
        }
        
        public BookContractorClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BookContractorClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BookContractorClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BookContractorClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public TestShopService.BookConctractor.Book[] GetAllBooks() {
            return base.Channel.GetAllBooks();
        }
        
        public System.Threading.Tasks.Task<TestShopService.BookConctractor.Book[]> GetAllBooksAsync() {
            return base.Channel.GetAllBooksAsync();
        }
        
        public TestShopService.BookConctractor.Book[] FindBooks(TestShopService.BookConctractor.BookType bookType, string title, string publisher) {
            return base.Channel.FindBooks(bookType, title, publisher);
        }
        
        public System.Threading.Tasks.Task<TestShopService.BookConctractor.Book[]> FindBooksAsync(TestShopService.BookConctractor.BookType bookType, string title, string publisher) {
            return base.Channel.FindBooksAsync(bookType, title, publisher);
        }
    }
}
